### ISSUE TITLE
Fernández method errors - discrepancy between rjdbench and rjd3bench

### ISSUE THREAD

**Issue by JavierGomezRoji** [rjdverse/rjd3bench#22]
Hi!

I'm Javier Gómez-Rojí, from the Spanish National Statistics Institute. We are trying to migrate from using rjdbench to rjd3bench, but we hace noticed that, when using the Fernández method of temporal disaggregation, the errors computed by the new package differ from those computed by the old one.

This is a simple code snippet to reproduce the issue:

```
# qna data, fernandez with quarterly indicator

# rjd3bench
library(rjd3bench)
data("qna_data")
Y<-ts(qna_data$B1G_Y_data[,"B1G_FF"], frequency=1, start=c(2009,1))
x<-ts(qna_data$TURN_Q_data[,"TURN_INDEX_FF"], frequency=4, start=c(2009,1))
td1<-rjd3bench::temporaldisaggregation(Y, indicators=x, model = "Rw")
rjd3.pred <- td1$estimation$disagg
rjd3.error <- td1$estimation$edisagg

# rjdbench
library(rjdbench)
td1_rjdbench<-rjdbench::jd3_tempdisagg(Y, indicators=list(x), model = "Rw")
rjd.pred <- result(td1_rjdbench, "disagg")
rjd.error <- result(td1_rjdbench, "edisagg")

# diff
rjd3.pred - rjd.pred
rjd3.error - rjd.error
```

Using rjdbench v0.2.0 and rjd3bench v2.0.0, we get the following differences:

![image](https://github.com/rjdverse/rjd3bench/assets/157582621/cebc6474-8fe3-4752-905d-cc1a4384036c)

We find the differences in predictions to be negligible, but the differences in errors are quite big. Have you changed something about the calculation of errors or are we doing something wrong?

Thanks in advance,
Javier

**Comment by palatej** [comment]
Hi Javier,

I can' retrieve the code of rjdbench, which was based on a very early version of jd+3.x (the code changed significantly since that time). The new version (rjd3bench) should be the correct one. At least, the results correspond to what we have in JD+ 2.x/3.x (GUIs).
To be noted that the stdev of the ar parameter (rho) will be corrected in the next version of rjd3bench (coming soon).
